### ISSUE TITLE
merge-20160113: bootloader does not boot

### ISSUE THREAD

**Issue by vonfritz** [xapp-le/owl#5]
When I try to boot using the bootloader buildet from branch  merge-20160113, then it stops with message:

> atc_2603c VERSION A not support this voltage.
> pmu_init() Can't init PMU, ret=-1 type=2

see [http://forum.linux-xapple.org/t/actions-release-version-0113-has-been-merge-in-a-testing-branch/261/2](url) for log.

It boots when I "flash" the bootloader.bin buildet from the master branch.
The problem resides clearly in the bootloader see also ddr_clk set to 0
I am not able to analyze this issue deeper. This is proprietary stuff.

**Comment by vonfritz** [comment]
OK, solved.
When you build a kernel following this tutorial
[http://wiki.linux-xapple.org/w/index.php/Build_Howto](url)
Then it takes by default the bootloader.ini from the linux folder (s500/boards/linux/) but the linux folder is not updated you have "only" updated the ubuntu folder.
Greetings

**Comment by vonfritz** [comment]
With this "fix" it builds bootloader.bin correctly.
https://github.com/vonfritz/owl/commit/b54a75a16d615d5a51613e654e4fa5d3f12e3b57

**Comment by william-wyliang** [comment]
I guess that's because Actions mainly worked and only tested on their 'Ubuntu' images. Thanks a lot for the finding. @vonfritz Could you send a pull request? I can help merge your contribution then. :)
